name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTERY_API_KEY: ${{ secrets.TESTERY_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Build and run tests
        run: ./gradlew test
